FROM wordpress:php7.4-apache

RUN apt update -y && apt install dos2unix -y

COPY --chown=www-data:www-data . /var/www/html/
COPY modsecurity/docker-php-entrypoint.dev /usr/local/bin/docker-entrypoint.sh

RUN rm -Rf /usr/src/wordpress/ && find /var/www/html -type d -exec chmod 755 {} \; && find /var/www/html -type f -exec chmod 644 {} \; && chmod 660 /var/www/html/wp-config.php && chmod 664 /var/www/html/.htaccess
RUN chmod +x /usr/local/bin/docker-entrypoint.sh && dos2unix /usr/local/bin/docker-entrypoint.sh

#ENTRYPOINT [ "/usr/local/bin/docker-php-entrypoint","apache2" ]